# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://dltasolutions.github.io
title: DLTA Solutions
email: dltasolutions@outlook.com
author: DLTA Solutions
description: ""
copyright: '&copy; 2017 DLTA Solutions, Inc. Tous droits réservés.'
credits: 'Site propulsé par Jekyll à partir du thème Bootstrap de <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/dltasolutions
